const data={
    products: [
        {
            _id:'1',
            name: 'CASIO INVERD',
            slug: 'sd',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'NGON ',
        },
        {
            _id:'2',
            name: 'CASIO NON ',
            slug: 'zxc',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 0,
            brand:'CASIO',
            rating:3,
            numReviews:20,
            description:'Hight quality',
        },
        {
            _id:'3',
            name: 'CASadadO INVERD',
            slug: 'scx',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'Hight quality',
        },
        {
            _id:'4',
            name: 'CASasdsacvcvxIO INVERD',
            slug: 'asdxxccas',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'Hight quality',
        },
     
    ],
};
export default data; 