const data={
    products: [
        {
            name: 'CASIO INVERD',
            slug: 'asdas',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'Hight quality',
        },
        {
            name: 'CASIO INVERD',
            slug: 'xxzc',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'Hight quality',
        },
        {
            name: 'CASIO INVERD',
            slug: 'zc',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'Hight quality',
        },
        {
            name: 'CASIO INVERD',
            slug: 'zxc',
            category: 'Shirts',
            image:'/images/watch-6.jpg',
            price:120,
            countInStock: 10,
            brand:'CASIO',
            rating:4.5,
            numReviews:10,
            description:'Hight quality',
        },
     
    ],
};
export default data; 